mollie/WooCommerce

- MPM/mpm.php
- MPM/mpm_gateway.php
- MPM/mpm_return.php
- MPM/mpm_settings.php
Fixes return url search for order_id. If no orderid can be found. We try another method.
Some shops have a slash on the end and then the order_id. But some other shops have this slash omitted, in which case a question mark will follow. So we can check for the question mark if no order_id can be found with the slash.
> Fix no order_id on return page.

- mollie-payments-for-woocommerce/includes/mollie/wc/gateway/abstract.php
Getest in WooCommerce shop mét en zonder Polylang.
> Polylang compatibility - multilingual support for return and webhook url

- mollie-payments-for-woocommerce/includes/mollie/wc/gateway/abstract.php
If language code doesn't contain a dash, use full language code as slug
> Fix for collaboration with Polylang

- mollie-payments-for-woocommerce/includes/mollie/wc/helper/api.php
We would like to use this filter on the api key so we can change the api key based on a pick up location. Every pick up location uses different mollie accounts. Having a filter to change the api key doesn't really affect the security, because if a plugin would like to change the api key, they can simple do so by changing the database value of the api key setting.
> Api key filter added

- mollie-payments-for-woocommerce/includes/mollie/wc/plugin.php
Fix redundant "DESCRIBE *__mollie_pending_payment" error shown in logs when table is created
> Fix redundant database error shown in logs

- mollie-payments-for-woocommerce/includes/mollie/wc/gateway/abstract.php
- mollie-payments-for-woocommerce/includes/mollie/wc/gateway/abstractseparecurring.php
- mollie-payments-for-woocommerce/includes/mollie/wc/gateway/abstractsubscription.php
- mollie-payments-for-woocommerce/includes/mollie/wc/gateway/banktransfer.php
- mollie-payments-for-woocommerce/includes/mollie/wc/helper/data.php
- mollie-payments-for-woocommerce/includes/mollie/wc/helper/settings.php
- mollie-payments-for-woocommerce/includes/mollie/wc/plugin.php
- mollie-payments-for-woocommerce/readme.txt
Pull request for switch to WooCommerce 3.0 get_ methods, backwards compatible with older versions of WooCommerce.
Issue: https://github.com/mollie/WooCommerce/issues/89
> WC 3.0: Add support for WooCommerce 3.0 (backwards compatible)

- mollie-payments-for-woocommerce/includes/mollie/wc/gateway/banktransfer.php
Fix wrong date formatting in some cases. For example when the specified date format in WP is 'd/m/Y' then strtotime will parse a date like '05/11/2017' as 'm/d/Y' (see strtotime for details) which causes the month and date to be flipped. Instead, we should format the date in a specific accepted format (for example 'Y-m-d H:i:s') to prevent this problem. Afterwards it is correctly formatted for display using date_i18n and wc_date_format anyway.
Sidenote: I have not tested the change, but it should work.
> Fix wrong date formatting

- mollie-payments-for-woocommerce/includes/mollie/wc/gateway/abstract.php
Fixes #211 
This check prevents the mollie-for-woocommerce plugin from triggering a fatal error when the filter on https://github.com/woocommerce/woocommerce/blob/3.4.1/templates/checkout/thankyou.php#L83 is called.
> Fixes #211, Removes fatal error for thankyou page without valid order

- mollie-payments-for-woocommerce/includes/mollie/wc/gateway/sofort.php
Code change to return only the last 4 digits of the IBAN for the Sofort mail instead of entire IBAN.
Code to return last 4 digits of IBAN is now the same as used in Ideal gateway.
> Only return the last digits of IBAN in Sofort mail

- mollie-payments-for-woocommerce/includes/mollie/wc/helper/settings.php
Besides nl_NL_formal there is also de_DE_formal that must be converted to de_DE to work with Mollie
> Convert de_DE_formal to de_DE

- mollie-payments-for-woocommerce/includes/mollie/wc/plugin.php
- patchwork.json
- tests/php/Unit/Mollie_WC_PluginTest.php
WooCommerce allow to register gateways not only as class string names but
you can also register an instance of a class.
When we are looking for `Mollie_WC_Gateway_Applepay` to remove it using
`array_diff` we could cause an error because the `$gateways` list may
contains instances of classes.
Using array search will fix the problem.
The solution is unit tested
> Remove Apple Pay method securely without causing type errors

- composer.json
- mollie-payments-for-woocommerce/includes/mollie/wc/gateway/abstract.php
- tests/php/Functional/Mollie_WC_Gateway_AbstractTest.php
- tests/php/TestCase.php
- tests/php/Unit/Mollie_WC_Gateway_AbstractTest.php
- tests/php/bootstrap.php
- tests/php/stubs/woocommerce.php
The method `getActiveMolliePayment` could return two different type of
values, this make the solution unpredictable and you have to add additional
conditional statement.
Instead a more correct approach would be throw an `UnexpectedValueException`.
The main problem was to set a different message for caller about the
return value of `getActiveMolliePayment` that could help debugging and
support and also solve a WSOD in production.
Problem was the impossibility to create an unit tested solution.
To do that I created a new method for `paymentObject` and `activePaymentObject`
which move the concern of create instances outside of a consumer method.
Since I while working on that I found some duplication code that could
be improved and I also changed the way the order id is retrieved in a more …
> Always check if active payment instance has been set properly

- mollie-payments-for-woocommerce/assets/js/applepay.js
- mollie-payments-for-woocommerce/includes/mollie/wc/plugin.php
- tests/php/Unit/Mollie_WC_PluginTest.php
This solve the problem where for a sec the gateway will display in the page
for then being removed during the payment methods update made by WooCommerce
via AJAX.
> Remove apple pay only if the device does not support the payment method

- .travis.yml
- composer.json
- composer.lock
- mollie-payments-for-woocommerce/includes/mollie/OrderLineStatus.php
- mollie-payments-for-woocommerce/includes/mollie/wc/gateway/abstract.php
- mollie-payments-for-woocommerce/includes/mollie/wc/gateway/abstractseparecurring.php
- mollie-payments-for-woocommerce/includes/mollie/wc/helper/api.php
- mollie-payments-for-woocommerce/includes/mollie/wc/helper/paymentfactory.php
- mollie-payments-for-woocommerce/includes/mollie/wc/payment/OrderItemsRefunder.php
- mollie-payments-for-woocommerce/includes/mollie/wc/payment/PartialRefundException.php
- mollie-payments-for-woocommerce/includes/mollie/wc/payment/RefundLineItemsBuilder.php
- mollie-payments-for-woocommerce/includes/mollie/wc/payment/object.php
- mollie-payments-for-woocommerce/includes/mollie/wc/payment/order.php
- mollie-payments-for-woocommerce/includes/mollie/wc/payment/payment.php
- mollie-payments-for-woocommerce/includes/mollie/wc/plugin.php
- mollie-payments-for-woocommerce/mollie-payments-for-woocommerce.php
- phpunit.xml.dist
- tests/php/Functional/wc/payment/OrderItemsRefunderTest.php
- tests/php/Functional/wc/payment/RefundLineItemsBuilderTest.php
- tests/php/Stubs/stubs.php
- tests/php/Stubs/woocommerce.php
- tests/php/Unit/MollieWCHelperSettingsTest.php
- tests/php/Unit/wc/Mollie_WC_Plugin_Test.php
- tests/php/Unit/wc/helper/Mollie_WC_Helper_Settings_Test.php
- tests/php/bootstrap.php
The issue also solve a problem when the amount to refund for an item
is different than the price per unit defined in the mollie order.
Deprecate `Mollie_WC_Plugin::PLUGIN_ID . '_refund_created'` action, in
place of that there are multiple different actions performed based on
a specific context.
The changes introduce some DI expecially for `orders` endpoint.
Since `orders` endpoing are retrieved from the `ApiClient` when the
`paymentObject` is constructed it's possible that some of the internals
will throw an `ApiException`, for this reason I wrap the construction
of the object in a try/catch block.
Every catch block will log the exception but the returned value depends
by the context.
Method: `Mollie_WC_Gateway_AbstractSepaRecurring::handlePaidOrderWebhook`
Prevent useless and complicated …
> Refund chargeback the merchant for every order line item

- mollie-payments-for-woocommerce/includes/mollie/wc/plugin.php
WooCommerce Session instance is not created at configuration time,
there is a specific action we have to wait until the instance is
available through WooCommerce instance.
A check is needed in this case to ensure to execute our actions
> WooCommerce Session instance is lazy initialized

- composer.json
- composer.lock
- inc/utils.php
- src/Mollie/WC/Payment/Object.php
- src/Mollie/WC/Payment/Order.php
- src/Mollie/WC/Payment/Payment.php
- tests/php/Functional/WC/Payment/Mollie_WC_Payment_Order_Test.php
- tests/php/Functional/WC/Payment/Mollie_WC_Payment_Payment_Test.php
When onWebhookCanceled is called, we do nothing if order or payment has final status (completed|refunded|canceled), if not we proceed as usual.
Addresses [MOL-63][].
[MOL-63]: https://inpsyde.atlassian.net/browse/MOL-63
> Mol 63 woocommerce order status can be m

- composer.json
- composer.lock
- inc/utils.php
- src/Mollie/WC/Plugin.php
- tests/php/Functional/WC/Mollie_WC_Plugin_Test.php
- tests/php/Stubs/woocommerce.php
- tests/php/Unit/WC/Mollie_WC_Plugin_Test.php
When onMollieReturn now we get the order by key, not by id. 
`$order = $dataHelper->getWcOrder (wc_get_order_id_by_order_key ($key));`
This change will assure if some users use different order_ids to secure their website instead of the WC order ids, they will be able to retrieve the order. To test this method some static method calls (debug, dataHelper) were wrapped into functions (inc/utils)
Addresses [MOL-86][].
[MOL-86]: https://inpsyde.atlassian.net/browse/MOL-86
> Mol 86 code for review

- inc/utils.php
- inc/woocommerce.php
- src/Mollie/WC/Gateway/Abstract.php
- src/Mollie/WC/Helper/Settings.php
- src/Mollie/WC/Payment/Object.php
- src/Mollie/WC/Payment/Order.php
- src/Mollie/WC/Payment/Payment.php
- src/Mollie/WC/Plugin.php
- tests/php/Functional/WC/Mollie_WC_Plugin_Test.php
- tests/php/Functional/WC/Payment/Mollie_WC_Payment_Order_Test.php
- tests/php/Functional/WC/Payment/Mollie_WC_Payment_Payment_Test.php
- tests/php/Functional/inc/Functions_Test.php
- tests/php/Unit/WC/Gateway/Mollie_WC_Gateway_AbstractTest.php
- tests/php/Unit/WC/Mollie_WC_Plugin_Test.php
Rename of the inc/utils and inc/woocommerce
functions to avoid collisions with other functions
Tests are changed accordingly
Addresses [MOL-102][].
[MOL-102]: https://inpsyde.atlassian.net/browse/MOL-102
> Rename utils functions to avoid collisions

- src/Mollie/WC/Gateway/Abstract.php
```
Exception has occurred.
Deprecated: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated
```
Facing the above issue in php7.2.
It will be fixed by this PR.
> Deprecated: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated

- src/Mollie/WC/Gateway/Abstract.php
- tests/php/Unit/WC/Gateway/Mollie_WC_Gateway_AbstractTest.php
Addresses [MOL-134][].
The action now is outside orderNeedsPayment check,
so it fires whether it is a success or failure.
We create the action name dynamically.
[MOL-134]: https://inpsyde.atlassian.net/browse/MOL-134
> Move action outside if check

- src/Mollie/WC/Helper/Data.php
Addresses [MOL-128][].
Name built directly from filters, no hash needed,
so we can find them easily afterwards.
No need to unserialize, get_transient already does
the job.
Set_transient overrides the existent one, so no
need to delete it manually.
No need to serialize the set_transient parameter
so the try/catch is useless.
Transient expiration increased to one hour
[MOL-128]: https://inpsyde.atlassian.net/browse/MOL-128
> Optimize transients

- src/Mollie/WC/Plugin.php
- tests/php/Unit/WC/Mollie_WC_Plugin_Test.php
Addresses [MOL-138][].
We can't show apple pay on order-pay if is not a
suitable device, so we need to filter it as we
do on checkout
[MOL-138]: https://inpsyde.atlassian.net/browse/MOL-138
> Add check to order-pay page

- readme.md
> Klarna Pay later is now supported in Belgium as well

- src/Mollie/WC/Payment/Order.php
Instead of overwriting the `$amount` value, this allows for the check to happen without editing the variable, so later on in processing the refund it is not incorrectly put through `number_format()` a second time.
> Fixes #356, correctly refunds amount > 1000

- src/Mollie/WC/Gateway/Mealvoucher.php
- src/Mollie/WC/Helper/OrderLines.php
- src/Mollie/WC/Plugin.php
- Payments with no vouchers were not created due to 'no_category' being passed. Replaced with null
- Set default option in dropdowns to 'no category' instead of meal.
> Fix 'no category' and set default option

- mollie-payments-for-woocommerce.php
Addresses MOL-214
Just add a prefix to the `autoload()` function in the global namespace to avoid collisions and merge with the current `develop` branch.
> Rename autoload() function to avoid collisions

- src/Mollie/WC/Gateway/Abstract.php
- tests/php/Stubs/woocommerce.php
- tests/php/Unit/WC/Gateway/Mollie_WC_Gateway_Abstract_Test.php
Addresses [MOL-222][].
[MOL-222]: https://inpsyde.atlassian.net/browse/MOL-222
New setting in every gateway to choose
countries where to show itself.
In checkout, if the country is not allowed, the gw refrains from showing.
If the option is empty the workflow is as usual.
> Add allowed_countries option for gateways

- src/Mollie/WC/Payment/Payment.php
Since it is now always attempted to create an order it would be nice to have consistent transaction.description. For transactions via the orders API this will be the "Order "+ order.orderNumber. However when this is done via the payments API it is a translation of "Order" done via the WP method __() + orderNumber. I removed this translation.
> Consistent transaction descriptions

- src/Mollie/WC/Helper/OrderLines.php
This PR adds support for adding line items to an order representing gift cards (See https://woocommerce.com/products/gift-cards/)
> Add support for WooCommerce Gift Cards

- mollie-payments-for-woocommerce.php
By registering their module with the provided filter 'mollie_wc_plugin_modules', third-party plugins can access the container outside.
One way to register the module is to require "inpsyde/modularity" in the composer.json file and then implement the ExecutableModule in the class that has to access the $container instance. 
``` php
$module = new class implements ExecutableModule{
public function run(ContainerInterface $c): bool
{
//the container is available here $c->get('looking_for')
return true;
}
public function id(): string
{
return __CLASS__;
}
};
add_filter('mollie_wc_plugin_modules', function($modules) use ($module) {
array_push($modules, $module);
return $modules;
});
```
> MOL-681 add filter for third-party to register modules.

- src/Gateway/MolliePaymentGateway.php
If we tamper with the url then there is no order and we receive a null. In this case we return the text as is but we will not crash. Handles [MOL-724](https://inpsyde.atlassian.net/browse/MOL-724)
> MOL-724 second param can be null

- src/Gateway/MolliePaymentGateway.php
- src/Payment/OrderInstructionsService.php
- src/PaymentMethods/InstructionStrategies/BanktransferInstructionStrategy.php
Handles[ MOL-706](https://inpsyde.atlassian.net/browse/MOL-706)
We need the order in the banktransfer strategy and there was also a mismatch in the order of expected parameters.
> Fix display instructions after checkout

- src/Gateway/Surcharge.php
- src/PaymentMethods/AbstractPaymentMethod.php
We only fallback to the default if the setting does not exists, when is false. If the user wants it empty we do not fallback. Handles [MOL-715](https://inpsyde.atlassian.net/browse/MOL-715)
> MOL-715 fix fallback to default description

- src/Shared/Data.php
Save the methods with the issuers so there is no need
to call again for them. Then use the cached issuers in the
getMethodIssuers method, or call the API to retrieve them.
> MOL-685 get issuers in the main method API call

- .ddev/commands/web/wp
- DEVELOPERS.md
- bin/ddev-share
This PR adds a script that wraps `ddev share` and runs `wp search-replace` with the public URL - and restores the project's URL when finished:
`bin/ddev-share`
> Add ngrok wrapper script

- mollie-payments-for-woocommerce.php
- src/Activation/ActivationModule.php
- src/PaymentMethods/AbstractPaymentMethod.php
- src/PaymentMethods/Creditcard.php
- src/PaymentMethods/PaymentFieldsStrategies/CreditcardFieldsStrategy.php
- src/PaymentMethods/PaymentMethodI.php
- src/Shared/SharedDataDictionary.php
On new install components are enabled, on update disabled. So we check if is a new install and we set hasFields to default if there is no setting saved
Handles [MOL-846](https://inpsyde.atlassian.net/browse/MOL-846)
> MOL-846 Components enabled by default

- src/Payment/MollieObject.php
- src/Settings/Page/MollieSettingsPage.php
Some methods check if there is a subscription plugin.
Now that check can be true for plugins[ declaring themselves as subscription via filter.] Not only if WC_Subscriptions class is present.(https://github.com/mollie/WooCommerce/blob/0ec01f2001f8fd80aae1e960c53155ffda96e915/src/Shared/Data.php#L68) 
DirectDebit gateway [is enabled upon that same filter](https://github.com/mollie/WooCommerce/blob/0ec01f2001f8fd80aae1e960c53155ffda96e915/src/Shared/Data.php#L227).
The methods where we handle WC_Subs code still need to check for its classes to be present.
> MOL-891 Remove some coupling with WC_Subscription

- src/Gateway/Surcharge.php
The option is saved as string, we need a float.
Handles [MOL-936](https://inpsyde.atlassian.net/browse/MOL-936)
> MOL-936 cast surcharge limit to float

- src/Gateway/Voucher/MaybeDisableGateway.php
This error occurs when WooCommerce Checkout Block is active on checkout page edit screen.
PHP Fatal error: Uncaught Error: Call to a member function get_cart_contents() on null in /wp-content/plugins/mollie-payments-for-woocommerce/src/Gateway/Voucher/MaybeDisableGateway.php:92
This fix disables the Gateways on wp admin screens as cart object is always empty there.
> Fix Fatal Error in MaybeDisableGatway on checkout page edit screen

- src/PaymentMethods/AbstractPaymentMethod.php
Handles [PIWOO-234](https://mollie.atlassian.net/browse/PIWOO-234)
This Pr  changes the requirement that when a user has the default title in a gateway we would use the API title, not we respect that default title
[PIWOO-234]: https://mollie.atlassian.net/browse/PIWOO-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ignore default title to get api one

- .idea/DdevIntegration.xml
- .idea/WooCommerce.iml
- .idea/inspectionProfiles/Project_Default.xml
- .idea/php.xml
- .idea/phpunit.xml
- .idea/scopes/WordPress_Core.xml
This PR makes a few changes to the shared IDE configs:
* Configures path mappings for xDebug for the default "DDEV" Server provided by the DDEV Integration Plugin
* Sets up DDEV as the default interpreter source for the QA tools (psalm, phpcs, ...)
* Disables PHP CS Fixer
* Adds a custom scope for the WordPress installation
* Excludes that new Scope from QA tools inspections (<- this has previously led to PHPStorm inspections going crazy in WP core files. That is now gone)
* Disables PSR12 Inspections by PHPStorm. We let PHPCS take care of our Inpsyde Standard
> refactor: improve code quality tool configuration

- composer.json
- composer.lock
- psalm.xml
- resources/js/mollieBlockIndex.js
- src/Assets/AssetsModule.php
- src/Assets/MollieCheckoutBlocksSupport.php
Woocommerce checkout blocks require implementation of the following class: `Automattic\WooCommerce\Blocks\Payments\Integration\AbstractPaymentMethodType`
I implemented a class `MollieCheckoutBlocksSupport.php` which extends `AbstractPaymentMethodType` and registered its object using `PaymentMethodRegistry` in `woocommerce_blocks_payment_method_type_registration` hook. 
Some of the code was removed from the AssetModule and some of the code was moved from the AssetsModule to the MollieCheckoutBlocksSupport. 
Additionally I updated Woocommerce stubs and included `<file name="vendor/php-stubs/woocommerce-stubs/woocommerce-packages-stubs.php"/>` in psalm.xml.
> Fix/piwoo 125 - Add woocommerce checkout blocks support

- resources/scss/mollie-gateway-icons.scss
- src/Assets/AssetsModule.php
- src/PaymentMethods/AbstractPaymentMethod.php
- src/PaymentMethods/IconFactory.php
- src/PaymentMethods/PaymentMethodsIconUrl.php
- src/Settings/General/MollieGeneralSettings.php
- src/Shared/SharedDataDictionary.php
I changed the `\Mollie\WooCommerce\PaymentMethods\AbstractPaymentMethod::getIconUrl` method. It prioritises the image from API payment method. Icons will be loaded directly from the Mollie URL.
> Retrieve gateway icons from Mollie

- src/Gateway/Voucher/VoucherModule.php
Because of the `check_ajax_referer` bulk edit exited and returned -1 when Mollie Voucher was enabled.
Now we check if wp_doing_ajax before check_ajax_referer. In that case, bulk edit works as expected.
> Fix Site is broken on bulk edit when Mollie Voucher is activated

- resources/js/applepay.js
- src/Gateway/GatewayModule.php
I completely removed the method `\Mollie\WooCommerce\Gateway\GatewayModule::maybeDisableApplePayGateway`. It was not working anymore. Apple Pay is now removed on the frontend using Javascript and Apple Pay JS. `applepay.js` script handles **checkout** and **pay for order** page.
> Replace backend ApplePay filtering with the frontend filtering.

- src/Gateway/GatewayModule.php
- src/Gateway/MolliePaymentGateway.php
- src/Notice/FrontendNotice.php
- src/Notice/NoticeModule.php
- src/Payment/PaymentService.php
I created a new Notice type - FrontendNotice. This notice is sent to MolliePaymantGateway as a substitute for AdminNotice. 
It should show an error on the Pay for order page. 
Please check if this implementation could cause issue on the `\Mollie\WooCommerce\Gateway\MolliePaymentGateway::noOrderPaymentFailure` method.
> [PIWOO-349] Show notice to user if payment is not successful on the Pay for order page.

- src/Shared/Data.php
Instead of checking the path of the subscription plugin we now check the class. If a class exists, the plugin is activated.
> [PIWOO-196] Check if WC_Subscription class exists instead the subscription plugin file

- src/Gateway/Surcharge.php
When debugging was enabled on servers with PHP8+, some server responses included warnings which resulted in broken frontend functionality. This simple fix takes care of that:
```
if (!isset($gatewaySettings['payment_surcharge'])) {
return 0.0;
}
```
Other changes are from the code formatting.
> [PIWOO-348] FIX: Apple Pay button payment not possible as a guest user

- src/Settings/General/MollieGeneralSettings.php
Handles [PIWOO-353](https://mollie.atlassian.net/browse/PIWOO-353)
[PIWOO-353]: https://mollie.atlassian.net/browse/PIWOO-353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update initial_order_status setting description

- inc/settings/mollie_advanced_settings.php
- mollie-payments-for-woocommerce.php
- resources/js/advancedSettings.js
- src/Buttons/ApplePayButton/ApplePayDataObjectHttp.php
- src/MerchantCapture/Capture/Action/AbstractPaymentCaptureAction.php
- src/MerchantCapture/Capture/Action/CapturePayment.php
- src/MerchantCapture/Capture/Action/VoidPayment.php
- src/MerchantCapture/Capture/Type/ManualCapture.php
- src/MerchantCapture/Capture/Type/StateChangeCapture.php
- src/MerchantCapture/ManualCaptureStatus.php
- src/MerchantCapture/MerchantCaptureModule.php
- src/MerchantCapture/OrderListPaymentColumn.php
- src/MerchantCapture/UI/OrderActionBlock.php
- src/MerchantCapture/UI/StatusButton.php
- src/MerchantCapture/UI/StatusRenderer.php
- src/Payment/MollieOrderService.php
- src/Payment/MolliePayment.php
- src/Payment/PaymentModule.php
- src/Payment/PaymentService.php
- src/PaymentMethods/Kbc.php
- src/SDK/WordPressHttpAdapter.php
Here are some important notes about the PR:
- I created a new module MerchantCapture. Here you can find everything related to the Manual Capture except module settings which are located here: `inc/settings/mollie_advanced_settings.php`
- In `src/SDK/WordPressHttpAdapter.php` I added another `nobody` code. Please check it. If you think it can cause problems, we have to find another way. When we cancel the payment successful response is 202.
- In `src/Payment/MollieOrderService.php` I added a new action hook.
- In `src/Payment/PaymentModule.php` I added a filter for disabling shipping or capture settings.
- Most of the other changes were done by phpcbf.
> [PIWOO-229] WooCommerce - Merchant Capture

- src/MerchantCapture/Capture/Action/VoidPayment.php
- src/MerchantCapture/MollieCaptureSettings.php
- src/MerchantCapture/UI/StatusRenderer.php
https://mollie.atlassian.net/browse/PIWOO-386
> [PIWOO-386] Change strings from void into cancel

- mollie-payments-for-woocommerce.php
- src/MerchantCapture/Capture/Type/ManualCapture.php
- src/MerchantCapture/MerchantCaptureModule.php
- src/MerchantCapture/OrderListPaymentColumn.php
A new condition for manual capture was added. If we find a subscription product in the cart, we don't enable manual capture but proceed with automatic capture.
> [PIWOO-361] Disable authorisation when subscription product is in the cart

- src/MerchantCapture/MerchantCaptureModule.php
- src/Payment/MollieOrderService.php
Handles: [PIWOO-422](https://mollie.atlassian.net/browse/PIWOO-422)
In the Webhook method, we have to check if the payment object is a payment. If it is not, we don't have to run it. 
@mmaymo Maybe it would be better to remove the Payment type from this function https://github.com/mollie/WooCommerce/blob/develop/src/MerchantCapture/MerchantCaptureModule.php#L156
and check here what kind of object we received. What do you think?
[PIWOO-422]: https://mollie.atlassian.net/browse/PIWOO-422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PIWOO-422] TypeError merchant capture feature

- src/MerchantCapture/OrderListPaymentColumn.php
Handles: [PIWOO-423](https://mollie.atlassian.net/browse/PIWOO-423)
The issue occurred when Woocommerce Analytics was disabled and HPOS enabled.
This PR changes the type that we receive in the action `woocommerce_shop_order_list_table_custom_column` from `Automattic\WooCommerce\Admin\Overrides\Order` to `WC_Order`.
[PIWOO-423]: https://mollie.atlassian.net/browse/PIWOO-423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PIWOO-423] TypeError when WooCommerce Analytics is disabled

- resources/js/blocks/molliePaymentMethod.js
- src/Gateway/GatewayModule.php
- src/PaymentMethods/In3.php
Handles [PIWOO-439](https://mollie.atlassian.net/browse/PIWOO-439)
[PIWOO-439]: https://mollie.atlassian.net/browse/PIWOO-439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add validate error on in3 future birthdate

- inc/utils.php
- src/Payment/OrderLines.php
- tests/php/Functional/Payment/PaymentServiceTest.php
Handles [PIWOO-501](https://mollie.atlassian.net/browse/PIWOO-501)
[PIWOO-501]: https://mollie.atlassian.net/browse/PIWOO-501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add missmatch to request lines

- src/PaymentMethods/InstructionStrategies/CreditcardInstructionStrategy.php
For some CC transactions, the `details.cardHolder` is missing (not null, missing). This patch handles this situation.
Fixes #937
> Fix: CreditcardInstructionStrategy.php - handle missing cardHolder field

- src/MerchantCapture/MerchantCaptureModule.php
- src/MerchantCapture/OrderListPaymentColumn.php
Handles: [PIWOO-424](https://mollie.atlassian.net/browse/PIWOO-424)
This PR passes a container to our `\Mollie\WooCommerce\MerchantCapture\OrderListPaymentColumn` class. Before rendering the Payment status column, we check if manual capture is enabled.
[PIWOO-424]: https://mollie.atlassian.net/browse/PIWOO-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PIWOO-424] Payment Status column displayed in orders overview when capturing payments immediately

- src/Gateway/Voucher/MaybeDisableGateway.php
Handles [PIWOO-427](https://mollie.atlassian.net/browse/PIWOO-427)
[PIWOO-427]: https://mollie.atlassian.net/browse/PIWOO-427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Check if array PIWOO-427

- languages/mollie-payments-for-woocommerce-de_DE.po
- src/PaymentMethods/InstructionStrategies/DefaultInstructionStrategy.php
Handles [PIWOO-530](https://mollie.atlassian.net/browse/PIWOO-530)
[PIWOO-530]: https://mollie.atlassian.net/browse/PIWOO-530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update translation string

- .editorconfig
Some of the six keys were missing.
> **tab_width:** ... This defaults to the value of indent_size and doesn't usually need to be specified.
https://editorconfig.org/#supported-properties
> Add all EditorConfig keys

- src/PaymentMethods/Directdebit.php
- src/PaymentMethods/Giftcard.php
- src/PaymentMethods/Klarnasliceit.php
- src/Settings/SettingsModule.php
If there is no value for logs yet, we default to 'yes' and so the logs will run by default
> Fix value if missing option

- src/PaymentMethods/Creditcard.php
- src/Settings/SettingsModule.php
- Fix Mollie components not active on ne installations
- Fix Debug Log is not working on new installs
See [PIWOO-573](https://mollie.atlassian.net/browse/PIWOO-573)
[PIWOO-573]: https://mollie.atlassian.net/browse/PIWOO-573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Mollie Components are not enabled by default on new installations

- src/Payment/RefundLineItemsBuilder.php
Force refund item quantity to integer as stated in https://github.com/mollie/WooCommerce/issues/992
> Update RefundLineItemsBuilder.php, Force refund item quantity to integer

- src/Payment/MollieObject.php
The URL that is being logged should be the same URL that is used in further logic.
> Apply filters to URL before logging it

- src/PaymentMethods/Applepay.php
This fixes an issue where php8.2 wil throw an error when ltrim function receives a null value.
This issues occurs because $edit_checkout_page_link can be null at the moment, because get_edit_post_link doesn't return anything if the user can't edit the post.
And when it gets passed to the esc_url function, it uses ltrim, which will throw an error.
I added an if statement to the notice, because it doesn't make sense to show a notice without a link.
> fix: ltrim(): Passing null to parameter #1 ($string) of type string is deprecated with ApplePay on PHP8.2

- src/Gateway/MolliePaymentGatewayHandler.php
Get the return URL as late as possible so that other actions can run  before.
> Broken compatibility with FunnelKit Upsells

- uninstall.php
Fix deprecation notice on uninstallation
> Plugin can't be removed when WP debugging is active

- src/Payment/MollieOrder.php
- src/Payment/MolliePayment.php
- do not set order as paid again on webhooks paid with chargebacks
> Incorrect Order Status Update After Chargeback Due to Conflicting Webhooks

- src/Payment/OrderLines.php
- src/Payment/PaymentLines.php
- allow negative rounding correction
- fix getting of shipping costs on the pay for order page
> Mollie Payments Failing Due to Negative unitPrice from WooCommerce Line Item Rounding

- src/Payment/PaymentProcessor.php
- src/Settings/Page/Section/Advanced.php
- src/Settings/Page/Section/Header.php
- tests/php/Functional/Payment/PaymentServiceTest.php
When a new user opens the plugin configuration for the first time:
- The Payments API is selected by default.
- The documentation link in the plugin points to the Payments API documentation, not the Orders API.
- Existing users with the Orders API already configured should not be affected by this change.
- A visual indicator or note (optional) could be added to suggest the Payments API is the recommended option.
> Default to payments api for new users (717)

- src/Payment/MollieObject.php
- src/Payment/MollieOrder.php
- src/Payment/MolliePayment.php
- src/Subscription/MollieSubscriptionGatewayHandler.php
- fixed the WCS retry logic not works in webhook context
- Add messages that shows failure reasons in the order note on Credit Card Payments.
> Improve Handling of Retryable Failed Payments

- .env.integration.example
- bootstrap.php
- composer.json
- composer.lock
- mollie-payments-for-woocommerce.php
- src/Payment/MollieOrderService.php
- tests/Integration/API/Mocks/MockedApi.php
- tests/Integration/API/Traits/APIMockTrait.php
- tests/Integration/Common/Factories/CouponFactory.php
- tests/Integration/Common/Factories/OrderFactory.php
- tests/Integration/Common/Factories/ProductFactory.php
- tests/Integration/Common/Fixtures/DiscountPresets.php
- tests/Integration/Common/Fixtures/ProductPresets.php
- tests/Integration/Common/Traits/CleansTestData.php
- tests/Integration/Common/Traits/CreateTestOrders.php
- tests/Integration/Common/Traits/CreateTestProducts.php
- tests/Integration/IntegrationMockedTestCase.php
- tests/Integration/README.md
- tests/Integration/bootstrap.php
- tests/Integration/spec/webhooks/WebhooksIntegrationTest.php
Multiple webhook calls arriving simultaneously for the same order could cause race conditions, leading to:
- Duplicate payment processing
- Inconsistent order states
- Double order status updates
- Potential financial discrepancies
Implemented a locking mechanism to ensure only one webhook processes an order at a time:
- **Order-level locking**: Added `acquireOrderLock()` and `releaseOrderLock()` using WordPress transients
- **Idempotency checks**: Prevent duplicate processing of the same payment ID
- **Conflict handling**: Return HTTP 409 when another webhook is already processing
- **Always release locks**: Use try/finally blocks to prevent deadlocks
- Added comprehensive integration test framework
- Created webhook race condition simulation tests
- Added factories for consistent test …
> Fix duplicate recurring payments from webhook race condition (718)

- src/Gateway/GatewayModule.php
If woo phone is empty or invalid, and our phone field is not empty and the phone is valid we save it, it does not make sense that we only save invalid phones
> Change validation logic for in3 phone field (PIWOO-478)

- src/Payment/MollieOrderService.php
- src/Payment/PaymentModule.php
- src/Payment/Request/Middleware/UrlMiddleware.php
- src/Payment/Webhooks/RestApi.php
- src/Payment/inc/services.php
- tests/Integration/Common/Factories/OrderFactory.php
- tests/Integration/Common/Traits/CreateTestOrders.php
- tests/Integration/phpunit.xml.dist
- tests/Integration/spec/webhooks/WebhooksIntegrationTest.php
- Added rest endpoint for getting webhooks
- keep old endpoint for fallback and existing payments
- Rest endpoint will search for order by transaction id and handle it
- add filter for switch back to old behavior
That should fix:
- problems with webhooks from payments and orders at same time, because only that wit the right transaction ID will be handled
- Rest should be faster
- easier url 
In future can the Woo API endpoint also search directly by transaction ID and not using the order Key.
Maybe remove check of payment meta that order ID is the same
> Modernize webhooks with rest endpoint

- src/Payment/Request/Middleware/AddressMiddleware.php
Whenever the phone is optional but we pass something in post or shipping address we have to check again, the API will fail if any number is not valid so we must send empty.
> Return empty if posted phone is invalid also in shipping address
