mollie/WooCommerce

mollie-payments-for-woocommerce/includes/mollie/wc/gateway/abstract.php
mollie-payments-for-woocommerce/includes/mollie/wc/gateway/abstractseparecurring.php
mollie-payments-for-woocommerce/includes/mollie/wc/gateway/abstractsubscription.php
mollie-payments-for-woocommerce/includes/mollie/wc/gateway/belfius.php
mollie-payments-for-woocommerce/includes/mollie/wc/gateway/creditcard.php
mollie-payments-for-woocommerce/includes/mollie/wc/gateway/ideal.php
mollie-payments-for-woocommerce/includes/mollie/wc/gateway/mistercash.php
mollie-payments-for-woocommerce/includes/mollie/wc/gateway/sofort.php
mollie-payments-for-woocommerce/includes/mollie/wc/helper/settings.php
mollie-payments-for-woocommerce/includes/mollie/wc/plugin.php
mollie-payments-for-woocommerce/mollie-payments-for-woocommerce.php

Added WooCommerce Subscriptions and Mollie recurring payments support.

WooCommerce Subscriptions and Mollie recurring payments support

---

mollie-payments-for-woocommerce/includes/mollie/wc/gateway/abstractseparecurring.php
mollie-payments-for-woocommerce/includes/mollie/wc/gateway/abstractsubscription.php
mollie-payments-for-woocommerce/includes/mollie/wc/helper/data.php

Fixed a bug where non-recurring iDeal payments didn't get processed.

Fix for simple product payment

---

mollie-payments-for-woocommerce/includes/mollie/wc/gateway/abstractseparecurring.php
mollie-payments-for-woocommerce/includes/mollie/wc/helper/data.php
mollie-payments-for-woocommerce/includes/mollie/wc/helper/settings.php

Get both recurring and non-recurring payment methods

---

mollie-payments-for-woocommerce/includes/mollie/wc/gateway/ideal.php

This helps to translate the field when using WPML.

Translate issuers_empty_option

---

mollie-payments-for-woocommerce/includes/mollie/wc/gateway/abstract.php
mollie-payments-for-woocommerce/includes/mollie/wc/gateway/banktransfer.php
mollie-payments-for-woocommerce/includes/mollie/wc/helper/settings.php
mollie-payments-for-woocommerce/includes/mollie/wc/plugin.php
mollie-payments-for-woocommerce/mollie-payments-for-woocommerce.php
mollie-payments-for-woocommerce/readme.txt

Disable storing customer details at Mollie

---

mollie-payments-for-woocommerce/includes/mollie/wc/gateway/banktransfer.php

Bank transfer expiry date in translated format, as discussed in:
https://github.com/mollie/WooCommerce/issues/96
https://github.com/mollie/WooCommerce/issues/74

Bank transfer expiry date in translated format

---

mollie-payments-for-woocommerce/includes/mollie/wc/helper/orderlines.php

preventing further crashes in checkout.
followup on #280

Additional `$product` check

---

.travis.yml
composer.json
phpunit.xml.dist
tests/php/TestCase.php

Addresses [MOL-89][].
[MOL-89]: https://inpsyde.atlassian.net/browse/MOL-89

convertWarningToExceptions false in phpunit #MOL-89

---

inc/utils.php
src/Mollie/WC/Helper/Settings.php
src/Mollie/WC/Plugin.php

Refactor to improve performance
Addresses [MOL-93][].
[MOL-93]: https://inpsyde.atlassian.net/browse/MOL-93

Mol 93 php process taking to much time o

---

mollie-payments-for-woocommerce.php
package.json
src/Mollie/WC/Helper/PaymentMethodsIconUrl.php
src/Mollie/WC/Plugin.php
tests/php/Unit/WC/Gateway/Mollie_WC_Gateway_AbstractTest.php
tests/php/Unit/WC/Helper/Payment_Method_Icon_Url_Test.php

Change version to 5.5.0

---

src/Mollie/WC/Gateway/Abstract.php

CRITICAL Uncaught Error: Call to undefined function idn_to_ascii() 
Addresses [MOL-101][].
[MOL-101]: https://inpsyde.atlassian.net/browse/MOL-101
Closes #343

Add check for idn_to_ascii()

---

mollie-payments-for-woocommerce.php
package.json
src/Mollie/WC/Plugin.php

Rename version and WC tested

---

src/Mollie/WC/Gateway/Abstract.php
src/Mollie/WC/Payment/Order.php

Addresses [MOL-71][].
[MOL-71]: https://inpsyde.atlassian.net/browse/MOL-71

[MOL-71] No webhook is called when payment

---

development/readme.md
src/Mollie/WC/Gateway/BankTransfer.php

Addresses [MOL-106][].
[MOL-106]: https://inpsyde.atlassian.net/browse/MOL-106

[MOL-106] Remove custom due date for bank 

---

mollie-payments-for-woocommerce.php
package.json
src/Mollie/WC/Plugin.php

Change version name and wc tested version

---

src/Mollie/WC/Gateway/Abstract.php

Addresses [MOL-143][].
"Secure payments provided by" in
mollie component fields can be
translated now.
[MOL-143]: https://inpsyde.atlassian.net/browse/MOL-143

Add translation domain to string

---

src/Mollie/WC/Gateway/Abstract.php

Addresses [MOL-150][].
Data does not show user details
[MOL-150]: https://inpsyde.atlassian.net/browse/MOL-150

Add log to debug api call order & payment data

---

mollie-payments-for-woocommerce.php
src/Mollie/WC/Plugin.php

Change version number

---

inc/utils.php
inc/woocommerce.php
src/Mollie/WC/Components/Styles.php
src/Mollie/WC/Gateway/Abstract.php
src/Mollie/WC/Gateway/Creditcard.php
src/Mollie/WC/Helper/Settings.php
tests/php/Functional/WC/components/Mollie_WC_Components_Styles_Test.php
tests/php/Stubs/woocommerce.php
tests/php/Unit/WC/Gateway/Mollie_WC_Gateway_CreditCard_Test.php

Addresses [MOL-185][].
wc_string_to_bool fatal error
static call to non static method error
[MOL-185]: https://inpsyde.atlassian.net/browse/MOL-185

Fixes for wc4.4 and wp5.5

---

src/Mollie/WC/Gateway/Mealvoucher.php
src/Mollie/WC/Plugin.php

Fix voucher 'gifts' to 'gift'

---

mollie-payments-for-woocommerce.php

Addresses [MOL-161][].
[MOL-161]: https://inpsyde.atlassian.net/browse/MOL-161

Delete wp translation files on activate & update

---

src/Mollie/WC/Gateway/Abstract.php

Addresses [MOL-114][].
[MOL-114]: https://inpsyde.atlassian.net/browse/MOL-114

Add debug and order note line when payment is giftcard

---

src/Mollie/WC/Gateway/Abstract.php

Log info when credit card fails

---

src/Mollie/WC/Helper/Data.php

Addresses [MOL-155][].
[MOL-155]: https://inpsyde.atlassian.net/browse/MOL-155

Check for array on retrieving payment methods

---

mollie-payments-for-woocommerce.php
src/Mollie/WC/Plugin.php

Release 5.8.2 Change version references

---

mollie-payments-for-woocommerce.php

Addresses [MOL-190][].
[MOL-190]: https://inpsyde.atlassian.net/browse/MOL-190

Disable update plugin translations

---

mollie-payments-for-woocommerce.php
src/Mollie/WC/Plugin.php

RELEASE [5.8.3][].
[5.8.3]: https://inpsyde.atlassian.net/browse/MOL-202

Change plugin version

---

src/Mollie/WC/Payment/Order.php

Addresses [MOL-207][].
[MOL-207]: https://inpsyde.atlassian.net/browse/MOL-207

Mol 207 token

---

src/Mollie/WC/Plugin.php

Addresses [MOL-205][].
[MOL-205]: https://inpsyde.atlassian.net/browse/MOL-205

Add hook for payment gateways

---

src/Mollie/WC/Plugin.php

Update payments hook

---

src/Mollie/WC/Helper/Data.php

Add filter for ecur subscription

---

resources/js/applepayDirect.js
resources/js/applepayDirectCart.js
resources/js/maybeShowApplePayButton.js

Addresses [MOL-211][].
[MOL-211]: https://inpsyde.atlassian.net/browse/MOL-211
Return from the script if we are in an environment were we cannot pay with ApplePay

Mol 211 variations and applepay

---

src/Mollie/WC/Payment/RefundLineItemsBuilder.php
tests/php/Functional/WC/Payment/Mollie_WC_Payment_RefundLineItemsBuilder_Test.php

Addresses [MOL-196][].
[MOL-196]: https://inpsyde.atlassian.net/browse/MOL-196

Delete description field from toCancel lines

---

src/Mollie/WC/Plugin.php

Addresses [MOL-142][].
If is a payment we cannot ship it, so we bail.
Delete the WC check as this method will not
run if WC<3.0
[MOL-142]: https://inpsyde.atlassian.net/browse/MOL-142

Add check for payments on ShipandCaptureOrder

---

src/Mollie/WC/Plugin.php

hotfix/check_option_isset
On installation the option might not be set

Add check option isset

---

src/Mollie/WC/Gateway/Abstract.php

Create new paymentObject for payment type

---

mollie-payments-for-woocommerce.php
src/Mollie/WC/Plugin.php

Addresses [MOL-235][].
[MOL-235]: https://inpsyde.atlassian.net/browse/MOL-235

Change plugin and WC tested version

---

DEVELOPERS.md

Update developers doc

---

inc/utils.php
src/Mollie/WC/Helper/Api.php
src/Mollie/WC/Helper/Settings.php
src/Mollie/WC/Plugin.php

Addresses [MOL-188][].
[MOL-188]: https://inpsyde.atlassian.net/browse/MOL-188

Update profile ID when api key changes

---

mollie-payments-for-woocommerce.php

Addresses [MOL-240](https://inpsyde.atlassian.net/browse/MOL-240).
Just added a prefix to functions in the global namespace.

Add mollie* prefix to the global functions

---

docker/Dockerfile_wp
yarn.lock

Remove Composer installer hash check

---

mollie-payments-for-woocommerce.php
src/Mollie/WC/Plugin.php

Addresses [MOL-254][].
[MOL-254]: https://inpsyde.atlassian.net/browse/MOL-254

Pre-release 6.0

---

src/Mollie/WC/ApplePayButton/AjaxRequests.php

Addresses [MOL-165][]
[MOL-165]:: https://inpsyde.atlassian.net/browse/MOL-165

send apple just domain str in subfolder installs

---

inc/utils.php
src/Mollie/WC/Gateway/Giftcard.php
src/Mollie/WC/Gateway/Ideal.php
src/Mollie/WC/Gateway/Kbc.php

Addresses [MOL-260](https://inpsyde.atlassian.net/browse/MOL-260)

show dropdown only if enabled

---

src/Mollie/WC/Gateway/Abstract.php
src/Mollie/WC/Helper/Data.php

Adresses [MOL-264](https://inpsyde.atlassian.net/browse/MOL-264)

change deprecated optional parameter

---

src/Mollie/WC/Helper/Settings.php

Addresses [MOL-276](https://inpsyde.atlassian.net/browse/MOL-276)

Change url on settings links

---

src/Mollie/WC/Payment/Order.php
src/Mollie/WC/Payment/Payment.php

Fixes [MOL-271](https://inpsyde.atlassian.net/browse/MOL-271)

Check isset token

---

src/Mollie/WC/Gateway/Abstract.php

Fixes [MOL-226](https://inpsyde.atlassian.net/browse/MOL-226)

Don't change status if is partial refund

---

src/Mollie/WC/Gateway/AbstractSubscription.php

Handles [MOL-263](https://inpsyde.atlassian.net/browse/MOL-263)

take the mandate with the original payment method

---

src/Mollie/WC/Payment/Order.php
src/Mollie/WC/Payment/Payment.php

Handles [MOL-306](https://inpsyde.atlassian.net/browse/MOL-306)

Update payment with order id info

---

src/Mollie/WC/Payment/Object.php

Handles [MOL-319](https://inpsyde.atlassian.net/browse/MOL-319)

Fix call method for wc subscription

---

src/Mollie/WC/Payment/RefundLineItemsBuilder.php
tests/php/Functional/WC/Payment/Mollie_WC_Payment_RefundLineItemsBuilder_Test.php

Handle [MOL-297](https://inpsyde.atlassian.net/browse/MOL-297)

Change quantity on partial refund as in Woo

---

src/Mollie/WC/Helper/MaybeFixSubscription.php
src/Mollie/WC/Plugin.php

Handles [MOL-322](https://inpsyde.atlassian.net/browse/MOL-322)

update meta on broken subscriptions

---

src/Mollie/WC/Helper/MaybeFixSubscription.php

Handles [MOL-335](https://inpsyde.atlassian.net/browse/MOL-335)

only run fix if there is parent

---

src/Mollie/WC/Helper/GatewaySurchargeHandler.php

Handles [MOL-334](https://inpsyde.atlassian.net/browse/MOL-334)

add default value for order item meta action

---

resources/js/mollie-components.js

Handles [MOL-327](https://inpsyde.atlassian.net/browse/MOL-327)

check container visible on checkout update

---

mollie-payments-for-woocommerce.php
src/Mollie/WC/Plugin.php

Handles [MOL-336](https://inpsyde.atlassian.net/browse/MOL-336)

update version number

---

src/Mollie/WC/Payment/Payment.php

Handles [MOL-324](https://inpsyde.atlassian.net/browse/MOL-324)

order meta false when is payment

---

src/Mollie/WC/Helper/Settings.php

Handle (MOL-317)[https://inpsyde.atlassian.net/browse/MOL-317]

update klarna warning message

---

src/Mollie/WC/Payment/Object.php
src/Mollie/WC/Payment/Order.php
src/Mollie/WC/Payment/Payment.php

Handles [MOL-340](https://inpsyde.atlassian.net/browse/MOL-340)

Override status cancelled setting if manual change MOL-340

---

src/Mollie/WC/Plugin.php

Handles [MOL-387](https://inpsyde.atlassian.net/browse/MOL-387)

enqueue icons css only in checkout context

---

.github/workflows/ci.yml
.idea/WooCommerce.iml
.idea/php.xml
composer.json
composer.lock
mollie-payments-for-woocommerce.php
src/Mollie/WC/ActivationHandle/ConstraintsChecker.php

Handles [MOL-388](https://inpsyde.atlassian.net/browse/MOL-388)

upgrade php and wordpress requirements

---

src/Mollie/WC/Gateway/AbstractSubscription.php
src/Mollie/WC/Payment/Object.php
src/Mollie/WC/Payment/Order.php

Handles [MOL-281](https://inpsyde.atlassian.net/browse/MOL-281)

add mandate id meta to subscriptions

---

inc/utils.php
src/Mollie/WC/Plugin.php

Handles [MOL-421](https://inpsyde.atlassian.net/browse/MOL-421)

remove action if option disabled

---

resources/js/applepayDirect.js

Handles [MOL-339](https://inpsyde.atlassian.net/browse/MOL-339)

send updated id in case of variable product

---

resources/js/paypalButton.js
resources/js/paypalButtonCart.js

Handles [MOL-395](https://inpsyde.atlassian.net/browse/MOL-395)

wait 3 seconds to make button responsive

---

inc/settings/mollie_advanced_settings.php
resources/js/gatewaySurcharge.js
resources/js/settings.js
src/Mollie/WC/ApplePayButton/AjaxRequests.php
src/Mollie/WC/ApplePayButton/ResponsesToApple.php
src/Mollie/WC/Gateway/Abstract.php
src/Mollie/WC/Helper/GatewaySurchargeHandler.php
src/Mollie/WC/Helper/Settings.php

Handles [MOL-333](https://inpsyde.atlassian.net/browse/MOL-333)

Surcharge feature improvements

---

readme.md

Handles [MOL-482](https://inpsyde.atlassian.net/browse/MOL-482)

move instruction video

---

src/Shared/Data.php

the bug is: an empty array of methods is saved to the cache, and retrieved (assuming this does work). But then the if(!$methods) condition (with $methods being an empty array) evaluates to true, and the http request to the API is made over and over again. (Once with every new consumer hitting a page.)

Fix empty arrays not being treated as valid cache results

---

src/Payment/PaymentService.php

Handles [MOL-713](https://inpsyde.atlassian.net/browse/MOL-713)

MOL-713 fix ApiException use call

---

src/Payment/PaymentService.php

Handles [MOL-723](https://inpsyde.atlassian.net/browse/MOL-723)

MOL-723 include surcharge max limit on blocks

---

src/Gateway/MolliePaymentGateway.php

We can receive an empty string too. Handles [MOL-725](https://inpsyde.atlassian.net/browse/MOL-725)

MOL-725 check for empty instead of null only

---

inc/settings/mollie_advanced_settings.php
mollie-payments-for-woocommerce.php
src/Gateway/GatewayModule.php
src/Payment/PaymentModule.php
src/Settings/Page/MollieSettingsPage.php
src/Settings/Settings.php
src/Settings/SettingsModule.php
src/Shared/SharedDataDictionary.php
src/Uninstall/CleanDb.php
src/Uninstall/UninstallModule.php
uninstall.php

Handles [MOL-96](https://inpsyde.atlassian.net/browse/MOL-96)

MOL-96 add uninstall and remove options setting

---

src/Shared/SharedDataDictionary.php

Handles [MOL-96](https://inpsyde.atlassian.net/browse/MOL-96)
Adding some option names that were missing.

MOL-96 add missing option names

---

src/Gateway/MolliePaymentGateway.php
src/Shared/SharedDataDictionary.php
src/Subscription/MollieSubscriptionGateway.php

handles [MOL-736](https://inpsyde.atlassian.net/browse/MOL-736)

MOL-736 check cart amount only if available

---

src/Payment/PaymentService.php

Handle [MOL-832](https://inpsyde.atlassian.net/browse/MOL-832)

MOL-832 do not correct fee if in classic checkout

---

src/Gateway/Surcharge.php

Handles [MOL-833](https://inpsyde.atlassian.net/browse/MOL-833)

MOL-833 check fee text it's a string or default

---

mollie-payments-for-woocommerce.php
src/Shared/SharedModule.php

Handles [MOL-728](https://inpsyde.atlassian.net/browse/MOL-728)

MOL-728 Update to version 7.1.0

---

src/Assets/AssetsModule.php

Handles [MOL-824](https://inpsyde.atlassian.net/browse/MOL-824)

MOL-824 Default title only if false setting

---

src/Payment/PaymentService.php

Show the order lines info in the debug log inside the already existent order log. Handles [MOL-737](https://inpsyde.atlassian.net/browse/MOL-737)

Add order lines to debug log

---

.idea/php.xml
src/Assets/AssetsModule.php
src/Gateway/GatewayModule.php
src/Gateway/OrderMandatoryGatewayDisabler.php
src/Payment/PaymentModule.php
src/PaymentMethods/Klarnapaylater.php
src/PaymentMethods/Klarnapaynow.php
src/PaymentMethods/Klarnasliceit.php
src/PaymentMethods/Voucher.php
src/Settings/Settings.php
src/Settings/SettingsModule.php
src/Subscription/SubscriptionModule.php

Handles [MOL-658](https://inpsyde.atlassian.net/browse/MOL-658)

MOL-658 filter gateways on api switch setting

---

src/Payment/MollieOrder.php
src/Payment/PaymentModule.php

Translation function was missing for some order note messages. Handles [MOL-709](https://inpsyde.atlassian.net/browse/MOL-709)

MOL-709 Add translation to untranslated order notes

---

src/Payment/OrderLines.php

Handles [MOL-719](https://inpsyde.atlassian.net/browse/MOL-719)

MOL-719 allow negative fees for discounts

---

resources/js/blocks/molliePaymentMethod.js
src/Shared/GatewaySurchargeHandler.php

Handles [MOL-516](https://inpsyde.atlassian.net/browse/MOL-516)

MOL-516 Add taxes to surcharge fees

---

src/Payment/MollieOrderService.php

Handles [MOL-852](https://inpsyde.atlassian.net/browse/MOL-852)

MOL-852 check is mollie gateway for title

---

src/PaymentMethods/Bancontact.php
src/PaymentMethods/Belfius.php
src/PaymentMethods/Eps.php
src/PaymentMethods/Giropay.php
src/PaymentMethods/Ideal.php
src/PaymentMethods/Kbc.php
src/PaymentMethods/Sofort.php

handles [MOL-840](https://inpsyde.atlassian.net/browse/MOL-840)

MOL-840 confirmationdelay true in sepa methods

---

src/Gateway/MolliePaymentGateway.php
src/SDK/Api.php
src/Settings/Page/MollieSettingsPage.php

Handles [MOL-878](https://inpsyde.atlassian.net/browse/MOL-878)

MOL-878 update dashboard link

---

src/Gateway/MolliePaymentGateway.php
src/PaymentMethods/Creditcard.php
src/SDK/Api.php
src/Settings/Page/MollieSettingsPage.php

Handles [MOL-428](https://inpsyde.atlassian.net/browse/MOL-428)

MOL-428 Add UTM params to mollie.com links

---

src/Settings/Page/MollieSettingsPage.php

Handles [MOL-893](https://inpsyde.atlassian.net/browse/MOL-893)

MOL-893 Link to user account api keys in settings

---

src/PaymentMethods/Banktransfer.php
src/Settings/General/MollieGeneralSettings.php

Handles [MOL-867](https://inpsyde.atlassian.net/browse/MOL-867)

MOL-867 rename expiry time in settings description

---

src/Gateway/GatewayModule.php

Handles [MOL-560](https://inpsyde.atlassian.net/browse/MOL-560)

MOL-560 check expiry enabled before due-date

---

inc/utils.php
src/Assets/AssetsModule.php
src/Gateway/GatewayModule.php
src/Payment/PaymentModule.php
src/PaymentMethods/AbstractPaymentMethod.php
src/PaymentMethods/Creditcard.php
src/PaymentMethods/Giftcard.php
src/PaymentMethods/Ideal.php
src/PaymentMethods/Kbc.php
src/Settings/General/MollieGeneralSettings.php
src/Settings/SettingsModule.php
src/Shared/Data.php

Handles [MOL-854](https://inpsyde.atlassian.net/browse/MOL-854)

MOL-854 Mollie querying gateway settings on every page load

---

src/Buttons/ApplePayButton/AppleAjaxRequests.php
src/Gateway/Surcharge.php
src/Payment/PaymentService.php
src/Shared/GatewaySurchargeHandler.php

Handles [MOL-899](https://inpsyde.atlassian.net/browse/MOL-899)

MOL-899 Include tax in fee value

---

src/Payment/MolliePayment.php

Handles [MOL-904](https://inpsyde.atlassian.net/browse/MOL-904)

MOL-904 check is mollie gateway before handling

---

src/Gateway/Surcharge.php

Handles [MOL-899](https://inpsyde.atlassian.net/browse/MOL-899)

MOL-899 consider multiple tax for surcharge

---

mollie-payments-for-woocommerce.php
src/Gateway/Voucher/VoucherModule.php

Payment methods are not hardcoded anymore and might not be present. Handles [MOL-929](https://inpsyde.atlassian.net/browse/MOL-929?focusedCommentId=203173&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-203173)

REL-7.3.2 check voucher exists before using

---

src/Settings/Settings.php

Handles [MOL-937](https://inpsyde.atlassian.net/browse/MOL-937)

MOL-937 remove description in select countries

---

src/SDK/WordPressHttpAdapter.php
tests/php/Functional/SDK/SdkTest.php
tests/php/Stubs/woocommerce.php

Handles [MOL-947](https://inpsyde.atlassian.net/browse/MOL-947)

MOL-947 check types before sending to sdk

---

src/Payment/OrderLines.php

Handles [MOL-952](https://inpsyde.atlassian.net/browse/MOL-952)

MOL-952 dont calculate fee tax if is zero

---

src/Shared/GatewaySurchargeHandler.php

Handles [MOL-953](https://inpsyde.atlassian.net/browse/MOL-953)

MOL-953 filter before applying functions to array key

---

src/Subscription/MollieSubscriptionGateway.php

Handles [MOL-948](https://inpsyde.atlassian.net/browse/MOL-948)

MOL-948 remove duplicated debug log for renewal orders

---

src/Payment/MollieOrder.php
src/Payment/MolliePayment.php

Handles [MOL-897](https://inpsyde.atlassian.net/browse/MOL-897)

MOL-897 check order status before canceling

---

src/Payment/MollieOrderService.php

Handles [MOL-974](https://inpsyde.atlassian.net/browse/MOL-974)

MOL-974 bail if not our gw in webhook

---

src/Settings/SettingsModule.php

Handles [MOL-965](https://inpsyde.atlassian.net/browse/MOL-965)

MOL-965 load test notice on settings update

---

src/Buttons/PayPalButton/PayPalAjaxRequests.php
src/Payment/MollieOrderService.php

Handles [MOL-505](https://inpsyde.atlassian.net/browse/MOL-505)

MOL-505 update paypal billing if missing

---

src/Shared/Data.php

Handles [MOL-991](https://inpsyde.atlassian.net/browse/MOL-991)

MOL-991 check blocks on class Package instead

---

src/Gateway/Surcharge.php

Handles [MOL-962](https://inpsyde.atlassian.net/browse/MOL-962)

MOL-962 add fee description in new paragraph

---

src/PaymentMethods/Directdebit.php

Handles [MOL-975](https://inpsyde.atlassian.net/browse/MOL-975)

MOL-975 remove non usable settings

---

src/Shared/Data.php

Handles [MOL-993](https://inpsyde.atlassian.net/browse/MOL-993)

MOL-993 use wc function to restore stock

---

src/Gateway/Voucher/MaybeDisableGateway.php

Handles [MOL-985](https://inpsyde.atlassian.net/browse/MOL-985)

MOL-985 remove voucher from pay page

---

src/Payment/MollieOrder.php
src/Payment/MollieOrderService.php

Handles [MOL-505](https://inpsyde.atlassian.net/browse/MOL-505)

override billing only on express MOL-505

---

mollie-payments-for-woocommerce.php

Handles [MOL-1026](https://inpsyde.atlassian.net/browse/MOL-1026)

update version number beta2 -1026

---

src/PaymentMethods/Giftcard.php

Handles [PIWOO-140](https://mollie.atlassian.net/browse/PIWOO-140)
[PIWOO-140]: https://mollie.atlassian.net/browse/PIWOO-140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix variable name typo P-140

---

src/Payment/PaymentService.php
src/SDK/Api.php

Handles [MOL-980](https://inpsyde.atlassian.net/browse/MOL-980)

Bail and log if 400, 500 error code from API -980

---

src/Subscription/MollieSubscriptionGateway.php

Handles [MOL-1012](https://inpsyde.atlassian.net/browse/MOL-1012)

Add log for failed mandate -1012

---

src/Gateway/GatewayModule.php

Handles [MOL-994](https://inpsyde.atlassian.net/browse/MOL-994)

Hide banktransfer on pay-page only if expiry setting -994

---

composer.lock
src/Shared/GatewaySurchargeHandler.php

Handles [PIWOO-181](https://mollie.atlassian.net/browse/PIWOO-181)
[PIWOO-181]: https://mollie.atlassian.net/browse/PIWOO-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix update surcharge fee handling

---

src/Payment/MollieObject.php
src/Payment/PaymentService.php

Handles [PIWOO-110](https://mollie.atlassian.net/browse/PIWOO-110)
[PIWOO-110]: https://mollie.atlassian.net/browse/PIWOO-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Save new mandate data in subscription order

---

src/Activation/ConstraintsChecker.php

I changed $wcConstraint in ConstraintsChecker from 3.0 to 3.9.

Change Woocommerce minimum version to 3.9.

---

resources/scss/mollie-components.scss

@mmaymo Simple fix that puts the CVV and the Expiry date fields back in the same line.

Fix broken credit card fields layout.

---

src/Payment/MollieOrderService.php

Checks if streetAdditional property exists and write it to address_1.

Write streetAdditional to address_2 field.

---

src/PaymentMethods/Banktransfer.php

add_filter function called wrong filter. I added `mollie_wc_gateway_` prefix to fix it.

Fix filter name. It was not called.

---

src/Gateway/GatewayModule.php
src/Gateway/MolliePaymentGateway.php

Handles [PIWOO-103](https://mollie.atlassian.net/browse/PIWOO-103)
[PIWOO-103]: https://mollie.atlassian.net/browse/PIWOO-103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add metabox to show payment details

---

mollie-payments-for-woocommerce.php

Handles [PIWOO-360](https://mollie.atlassian.net/browse/PIWOO-360)
[PIWOO-360]: https://mollie.atlassian.net/browse/PIWOO-360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release 7.4.1

---

src/MerchantCapture/Capture/Type/StateChangeCapture.php
src/MerchantCapture/MerchantCaptureModule.php
src/Payment/MollieOrderService.php

The badge in WooCommerce is updated when capturing/voiding an authorized payment at Mollie

[PIWOO-367] Payment status badge not updated when capturing/voiding in Mollie dashboard

---

mollie-payments-for-woocommerce.php

Handles [PIWOO-413](https://mollie.atlassian.net/browse/PIWOO-413)
[PIWOO-413]: https://mollie.atlassian.net/browse/PIWOO-413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release 7.5.0

---

src/Log/WcPsrLoggerAdapter.php

Fix deprecated expression in WcPsrLoggerAdapter

---

src/Gateway/GatewayModule.php

Handles [PIWOO-428](https://mollie.atlassian.net/browse/PIWOO-428)
[PIWOO-428]: https://mollie.atlassian.net/browse/PIWOO-428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove typed order in3 method

---

mollie-payments-for-woocommerce.php

Handles [PIWOO-462](https://mollie.atlassian.net/browse/PIWOO-462)
[PIWOO-462]: https://mollie.atlassian.net/browse/PIWOO-462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add requires header PIWOO-146

---

inc/utils.php
src/Payment/OrderLines.php

Handles [PIWOO-461](https://mollie.atlassian.net/browse/PIWOO-461)
[PIWOO-461]: https://mollie.atlassian.net/browse/PIWOO-461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Avoid rounding issues

---

inc/utils.php
public/images/riverty.svg
resources/js/blocks/molliePaymentMethod.js
resources/js/rivertyCountryPlaceholder.js
src/Assets/AssetsModule.php
src/Assets/MollieCheckoutBlocksSupport.php
src/Gateway/GatewayModule.php
src/Gateway/MolliePaymentGateway.php
src/Payment/MollieOrder.php
src/Payment/PaymentService.php
src/PaymentMethods/In3.php
src/PaymentMethods/PaymentFieldsStrategies/RivertyFieldsStrategy.php
src/PaymentMethods/Riverty.php
src/Shared/SharedDataDictionary.php
webpack.config.js

Handles [PIWOO-510](https://mollie.atlassian.net/browse/PIWOO-510)
The fields filters and processing is moved to the payment method itself. Only the new method this time, refactoring of Billie, and In3 will follow
[PIWOO-510]: https://mollie.atlassian.net/browse/PIWOO-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add Riverty payment method

---

src/PaymentMethods/PaymentFieldsStrategies/In3FieldsStrategy.php
src/PaymentMethods/PaymentFieldsStrategies/PaymentFieldsStrategiesTrait.php
src/PaymentMethods/PaymentFieldsStrategies/RivertyFieldsStrategy.php

Handles [PIWOO-521](https://mollie.atlassian.net/browse/PIWOO-521)
[PIWOO-521]: https://mollie.atlassian.net/browse/PIWOO-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add birth from meta to fields in pay page PIWOO-521

---

src/Gateway/MolliePaymentGateway.php

Handle [PIWOO-556](https://mollie.atlassian.net/browse/PIWOO-556)
[PIWOO-556]: https://mollie.atlassian.net/browse/PIWOO-556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add br to wp_kses instructions

---

src/PaymentMethods/Ideal.php

Handles [PIWOO-557](https://mollie.atlassian.net/browse/PIWOO-557)
[PIWOO-557]: https://mollie.atlassian.net/browse/PIWOO-557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add ideal notice

---

mollie-payments-for-woocommerce.php

Handles [PIWOO-561](https://mollie.atlassian.net/browse/PIWOO-561)
[PIWOO-561]: https://mollie.atlassian.net/browse/PIWOO-561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update version and tested version

---

tests/e2e/README.md

Remove double dash in tests readme.md

Typo - Removed double dash in tests readme

---

resources/js/blocks/molliePaymentMethod.js

Set store location when no country is selected on block checkout see [PIWOO-619](https://mollie.atlassian.net/browse/PIWOO-619)
[PIWOO-619]: https://mollie.atlassian.net/browse/PIWOO-619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Load block Checkout payment methods despite no active country selection

---

src/Settings/Page/Section/PaymentMethods.php

Don't display old Klarna GWs on the Settings page 
see [PIWOO-565](https://mollie.atlassian.net/browse/PIWOO-565)
[PIWOO-565]: https://mollie.atlassian.net/browse/PIWOO-565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Do not show deprecated Klarna methods if disabled in Mollie profile

---

src/Log/WcPsrLoggerAdapter.php
src/MerchantCapture/MerchantCaptureModule.php
src/Payment/MollieOrderService.php

see [PIWOO-609](https://mollie.atlassian.net/browse/PIWOO-609)
[PIWOO-609]: https://mollie.atlassian.net/browse/PIWOO-609?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

don't do webhooks when order is in processing or completed state

---

src/Gateway/GatewayModule.php

enable swish by default. see [PIWOO-622](https://mollie.atlassian.net/browse/PIWOO-622)
[PIWOO-622]: https://mollie.atlassian.net/browse/PIWOO-622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove feature flag for Swish

---

src/Gateway/MolliePaymentGatewayHandler.php
src/PaymentMethods/PaymentFieldsStrategies/CreditcardFieldsStrategy.php

Fix dynamic properties deprecated warning for 'has_fields' prop

---

src/Payment/OrderLines.php
src/Payment/PaymentLines.php

Mark global fees as discounts in Mollie API line items

[8.0] negative fees not accepted anymore

---

src/Assets/AssetsModule.php

Fix card token not working on pay for order page PIWOO-511

Card validation fields are duplicating, on Pay for order page

---

src/Payment/OrderLines.php
src/Payment/PaymentLines.php

Check image url is valid  #1008

[8.0] Line item imageUrl field should be a valid URL

---

src/PaymentMethods/Billie.php
src/PaymentMethods/Klarna.php
src/PaymentMethods/Riverty.php
src/Settings/Page/Section/PaymentMethods.php
src/Settings/SettingsModule.php

- Fix feature flag for Klarna, Riverty and Billie for order mandatory
- Restrict loading of the settings page to admin only

[8.0] Klarna displayed on payments API

---

src/Gateway/inc/services.php
src/Settings/MollieSettingsPage.php
src/Settings/Page/AbstractPage.php
src/Settings/Page/Section/AbstractSection.php
src/Settings/Page/Section/Advanced.php
src/Settings/Page/Section/Notices.php
src/Settings/Page/Section/PaymentMethods.php
src/Settings/SettingsModule.php

Only load gateways late and when GW are needed in settings.
Now GW will be refreshed after a key change.
Fix fatal error.

[8.0] Error on refreshing gateway list

---

resources/js/blocks/molliePaymentMethod.js

Fix #1000 in Block checkout payment methods description

Twint Payment Method adds description although there is no description

---

src/Payment/OrderLines.php
src/Payment/PaymentLines.php

[8.0.1-bata] Order can't be placed with Payments API when 3rd party fee is applied

---

resources/js/blocks/molliePaymentMethod.js
src/Payment/OrderLines.php
src/Payment/PaymentLines.php
src/Shared/GatewaySurchargeHandler.php
tests/php/Functional/Shared/SurchargeHandlerTest.php

Fix surcharge fees in block checkout see #895

Mollie removing third-party fees

---

src/Payment/MollieOrderService.php

added code to filter out transaction webhooks for klarna when orders API is active again

[8.0] Stock Deducted Twice for Klarna Pay Later Orders

---

inc/utils.php
src/Payment/Request/Middleware/AddressMiddleware.php

Improved phone number formatting and detection for better E.164 support

Phone Number Validation is too Aggressive #1025

---

src/Gateway/GatewayModule.php
src/Payment/PaymentModule.php

improved getting of transaction id and added a missing return statement

Type error when transaction id missing

---

src/Gateway/GatewayModule.php

Pay for Order - Error 500 upon payment with in3 (Order API method)

---

src/Gateway/GatewayModule.php
src/Payment/Request/Middleware/CustomerBirthdateMiddleware.php
src/PaymentMethods/Constants.php
src/PaymentMethods/PaymentFieldsStrategies/In3FieldsStrategy.php
src/PaymentMethods/PaymentFieldsStrategies/RivertyFieldsStrategy.php
src/PaymentMethods/Riverty.php

Improved birthdate fields so that block checkout works again for riverty

[8.0] Transactions are not going through for Riverty on Block checkout

---

src/Gateway/MolliePaymentGatewayHandler.php
src/Subscription/MollieSepaRecurringGatewayHandler.php

fixing undefined property method_titles

Warning: Undefined property when using Open result with Bank Transfer

---

src/Gateway/Surcharge.php

Fix surcharge percentage without max limit not working

Payment Surcharge Percentage Not Applying at Checkout

---

src/Payment/PaymentProcessor.php
src/Shared/GatewaySurchargeHandler.php

Remove the not anymore necessary method for block checkout surcharge calculation

Please add a filter to bypass Surcharge Fee

---

src/Gateway/MolliePaymentGatewayHandler.php

Fatal Error on "Order History" Page When Navigating to Second Page

---

inc/utils.php
src/BlockService/CheckoutBlockService.php
src/Gateway/Voucher/MaybeDisableGateway.php
src/Gateway/Voucher/VoucherModule.php
src/Payment/OrderLines.php
src/Payment/PaymentLines.php
src/PaymentMethods/Voucher.php

- Activate Vouchers for Payments API
- add category Sports & Culture
- prepared multiple category's for Payments API

Enable voucher support on payments api for all customers

---

resources/js/gatewaySurcharge.js
src/Shared/GatewaySurchargeHandler.php
tests/php/Functional/Shared/SurchargeHandlerTest.php

Address issues with pay order page surcharges

---

src/Gateway/GatewayModule.php
src/Gateway/Voucher/MaybeDisableGateway.php
src/Payment/PaymentModule.php
src/Payment/PaymentProcessor.php
src/PaymentMethods/Constants.php
src/PaymentMethods/InstructionStrategies/PaybybankInstructionStrategy.php
src/PaymentMethods/Paybybank.php
src/PaymentMethods/PaymentRedirectStrategies/PaybybankRedirectStrategy.php

Algin Pay by Bank with Bank Transfer features

Align "Pay by Bank" Behavior with "Bank Transfer" to Prevent User Confusion and Duplicate Orders

---

src/Payment/OrderLines.php
src/Payment/PaymentLines.php
src/PaymentMethods/Constants.php
src/PaymentMethods/Voucher.php

-  Voucher categories only added when gateway is active
- clean the categories from myby wrong ones.

transactions are failing with 503 with 8.0.5 version

---

src/Gateway/inc/services.php

Just changed the feature flag to enabled by default

Enable vipps feature flag by default

---

src/Settings/Page/Section/Notices.php

Remove mention to klarna slice it and pay later.
Link to new general Klarna Wiki page.

Update klarna notice (PIWOO-653)

---

src/Payment/OrderLines.php
src/Payment/PaymentLines.php

Fix type error with Germanized

TypeError in OrderLines.php when processing vouchers with Germanized plugin
